import time
from common.logger import LogInfo


class RequestLoggingMiddleware:
    """
    Middleware for logging details about incoming requests and their responses.
    This middleware logs details such as method, path, headers, client IP, response status, and execution time.
    Attributes:
        get_response (callable): The next middleware or view in the Django request/response chain.
    """

    def __init__(self, get_response):
        """
        Initialize the middleware.
        Args:
            get_response (callable): The next middleware or view in the Django request/response chain.
        """
        self.get_response = get_response

    def __call__(self, request):
        """
        Process the incoming request, log details, and handle the response.
        Args:
            request (HttpRequest): The incoming request.
        Returns:
            HttpResponse: The response generated by the middleware.
        """
        start_time = time.time()
        response = self.get_response(request)
        execution_time = time.time() - start_time

        # Log request details
        LogInfo.info(
            f"Method: {request.method}, "
            f"Path: {request.path}, "
            f"Headers: {request.headers}, "
            f"Device IP: {self.get_client_ip(request)}, "
            f"Response Status: {response.status_code}, "
            f"Execution Time: {execution_time:.6f} seconds"
        )
        return response

    def get_client_ip(self, request):
        """
        Get the client's IP address from the request.
        Args:
            request (HttpRequest): The incoming request.
        Returns:
            str: The client's IP address.
        """
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip
